---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-son-config-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-son-config
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-son-config-local-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-son-config-local
  resources:
    requests:
      storage: 10Gi


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-son-download-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-download
  resources:
    requests:
      storage: 100Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-son-content-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-plex-content
  resources:
    requests:
      storage: 10Ti


