---
apiVersion: v1
kind: Service

metadata:
  name: media-son
  labels:
    app: media-son

spec:
  selector:
    app: media-son
  
  type: ClusterIP
  ports:
    - name: ui
      port: 8989
      targetPort: 8989
      #nodePort: 30003
      protocol: TCP
    
---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: media-son-access
  
spec:
  selector:
    app: media-son

    #type: NodePort
  type: LoadBalancer
  loadBalancerIP: 192.168.1.253
  ports:
    - port: 80
      targetPort: 8989
      #nodePort: 30003
      protocol: TCP



