---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nc-web-nfs-pv

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  #  mountOptions:
  #  - hard
  #  - nfsvers=4.1
  nfs:
    path: /mnt/nfsshare/kube/nextcloud/web
    server: 192.168.1.222
    #path: /kube/nextcloud
    #server: 192.168.1.85


