---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nc-db-nfs-pv

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: nc-db-nfs
  #  mountOptions:
  #  - hard
  #  - nfsvers=4.1
  nfs:
    path: /mnt/nfsshare/kube/nextcloud/db
    server: 192.168.1.222
    #path: /kube/nextcloud/db
    #server: 192.168.1.85

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nc-db-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: Filesystem
  #storageClassName: nc-db-nfs
  resources:
    requests:
      storage: 10Gi
  #storageClassName: nfs

