---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nc-db-pv

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nc-db
  nfs:
    path: /mnt/data/kube/nextcloud/db
    server: 192.168.1.222
   
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nc-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nc-db
  resources:
    requests:
      storage: 10Gi

