---
apiVersion: v1
kind: Service

metadata:
  name: registry

spec:
  selector:
    app: registry
  
  type: NodePort
  #externalIPs:
  # - 192.168.1.221
  #externalTrafficPolicy: Local
  ports:
    #- port: 5000
    #  targetPort: 5000
    #  nodePort: 30002
    #  protocol: TCP
    - port: 443
      targetPort: 443
      nodePort: 30002
      protocol: TCP
    
