---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-plex-config
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-plex-config
  local:
    path: /kube/plex/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sn04

---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-plex-content

spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-plex-content
  nfs:
    path: /plex
    server: 192.168.1.85
