---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: newsbot02-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: newsbot02-db
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: newsbot02-logs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: newsbot02-logs
  resources:
    requests:
      storage: 10Gi