---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: jenkins-data

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-data
  nfs:
#    path: /kube/pihole/pihole
#    server: 192.168.1.85
    path: /mnt/nfsshare/kube/jenkins/data
    server: 192.168.1.222
 

