---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-world01-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: factorio-world01-data
  nfs:
    path: /mnt/data/factorio/world01
    server: 192.168.1.222

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: factorio-world01-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: factorio-world01-data
  resources:
    requests:
      storage: 10Gi


