---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-etc-pihole-pvc
spec:
  accessModes:
  - ReadWriteOnce
    #storageClassName: Filesystem
  storageClassName: pihole-pihole
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-etc-dnsmasq-pvc
spec:
  accessModes:
  - ReadWriteOnce
    #storageClassName: Filesystem
  storageClassName: pihole-dnsmasq
  resources:
    requests:
      storage: 10Gi


