apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 192.168.1.247-192.168.1.253
    - name: pool2
      protocol: layer2
      addresses:
        - 192.168.1.200-192.168.1.219



