---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-get-config

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-get-config

  nfs:
    path: /mnt/data/media/get/config
    server: 192.168.1.222

---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-get-download

spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-download

  nfs:
    path: /mnt/data/media/download
    server: 192.168.1.222

