---
apiVersion: v1
kind: Service

metadata:
  name: media-get
  labels:
    app: media-get

spec:
  selector:
    app: media-get
  
  type: ClusterIP
  ports:
    - name: ui
      port: 6789
      targetPort: 6789
      #nodePort: 30003
      protocol: TCP
    
---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: media-get-access
  
spec:
  selector:
    app: media-get

    #type: NodePort
  type: LoadBalancer
  loadBalancerIP: 192.168.1.252
  ports:
    - port: 80
      targetPort: 6789
      #nodePort: 30003
      protocol: TCP



