---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-search
  labels:
    app: media-search

spec:
  replicas: 1

  selector:
    matchLabels:
      app: media-search

  template:
    metadata:
      labels:
        app: media-search

    spec:
      containers:
        - name: media-search
          image: linuxserver/nzbhydra2:version-v3.9.0
          ports:
              #- name: ui
            - containerPort: 5076
              protocol: TCP
          volumeMounts:
            - name: media-search-config
              mountPath: /config
            - name: media-download
              mountPath: /downloads
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      priorityClassName: high-priority
      volumes:
        - name: media-search-config
          persistentVolumeClaim:
            claimName: media-search-config-pvc
        - name: media-download
          persistentVolumeClaim:
            claimName: media-search-download-pvc

