---
apiVersion: v1
kind: ConfigMap
metadata:
  name: newsbot-worker-01-config-template
  namespace: default
data:
  NEWSBOT_POGO_ENABLED: 'true'
  NEWSBOT_POGO_HOOK: ""

  NEWSBOT_PSO2_ENABLED: 'true'
  NEWSBOT_PSO2_HOOK: "" 

  NEWSBOT_FFXIV_ALL: 'false'
  NEWSBOT_FFXIV_TOPICS: 'True'
  NEWSBOT_FFXIV_NOTICES: 'false'
  NEWSBOT_FFXIV_MAINTENANCE: 'false'
  NEWSBOT_FFXIV_UPDATES: 'false'
  NEWSBOT_FFXIV_STATUS: 'false'
  NEWSBOT_FFXIV_HOOK: ""

  NEWSBOT_REDDIT_SUB_0: "ProgrammerHumor"
  NEWSBOT_REDDIT_HOOK_0: ""

  NEWSBOT_YOUTUBE_URL_0: 'https://www.youtube.com/user/loadingreadyrun/'
  NEWSBOT_YOUTUBE_NAME_0: "LoadingReadyRun"
  NEWSBOT_YOUTUBE_HOOK_0: ""

  #NEWSBOT_TWITTER_API_KEY: "{{ twitter_api_key }}"
  #NEWSBOT_TWITTER_API_KEY_SECRET: ""
  #NEWSBOT_TWITTER_USER_NAME_0: "GenshinImpact"
  #NEWSBOT_TWITTER_USER_HOOK_0: ""

  NEWSBOT_INSTAGRAM_USER_NAME_1: madmax_fluffyroad
  NEWSBOT_INSTAGRAM_USER_HOOK_1: ""
  NEWSBOT_INSTAGRAM_TAG_NAME_1: corgi
  NEWSBOT_INSTAGRAM_TAG_HOOK_1: ""

  NEWSBOT_TWITCH_CLIENT_ID: ""
  NEWSBOT_TWITCH_CLIENT_SECRET: ""

