---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-web
  labels:
    app: nc-web

spec:
  replicas: 1  
  
  selector: 
    matchLabels:
      app: nc-web

  template:
    metadata:
      labels:
        app: nc-web
    
    spec:
      containers:
        #restartPolicy: Always
        - name: nextcloud
          #image: nextcloud:20.0.5-apache
          image: linuxserver/nextcloud:version-20.0.7
          env:
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_USER
              value: nextcloud
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST
              value: nc-db.default

            - name: REDIS_HOST
              value: nc-cache.default
          ports:
            - containerPort: 443

          volumeMounts:
            - name: nc-web-data
              #- name: nc-local-web-storage
              mountPath: /data
            - name: nc-web-config
              mountPath: /config
        
      volumes:
        #- name: nc-local-web-storage
        #  hostPath:
        #    path: /kube/nc/web/
        #    type: DirectoryOrCreate

        - name: nc-web-data
          persistentVolumeClaim:
            claimName: nc-web-data-pvc
        - name: nc-web-config 
          persistentVolumeClaim:
            claimName: nc-web-config-pvc

