---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nc-web-ingress
#  namespace: default
  annotations:
    kubernetes.io/ingress.class: haproxy

spec:
  rules:
  - host: cloud.home.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nc-web
          servicePort: 80

