---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nc-web-nfs-pv
  labels:
    app: web
    storage: nfs
    service: web
    name: nc-web-nfs-pv
  #app: nextcloud
  #service: web

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nc-web-nfs
  #  mountOptions:
  #  - hard
  #  - nfsvers=4.1
  nfs: 
    #path: /mnt/nfsshare/kube/nextcloud/web
    path: /mnt/data/kube/nextcloud/web
    server: 192.168.1.222
 
