---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nc-web-pv
  labels:
    app: web
    storage: nfs
    service: web
    name: nc-web-pv
  #app: nextcloud
  #service: web

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nc-web 
  nfs: 
    path: /mnt/data/kube/nextcloud/web
    server: 192.168.1.222
 
