---
apiVersion: v1
kind: Service

metadata:
  name: nc-web-access

spec:
  selector:
    app: nc-web 
 
  type: LoadBalancer
  loadBalancerIP: 192.168.1.249
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web-access

