
---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: media-plex-access-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: media-plex-svc

spec:
  selector:
    app: media-plex

  type: LoadBalancer
  loadBalancerIP: 192.168.1.202
  ports:
    - port: 80
      targetPort: 32400
      protocol: TCP
      name: ui2
    - port: 32400
      targetPort: 32400
      protocol: TCP
      name: ui
    - port: 3005
      targetPort: 3005
      protocol: TCP
      name: tcp0
    - port: 8324
      targetPort: 8324
      protocol: TCP
      name: tcp1
    - port: 32469
      targetPort: 32469
      protocol: TCP
      name: tcp2

---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: media-plex-access-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: media-plex-svc

spec:
  selector:
    app: media-plex

  type: LoadBalancer
  loadBalancerIP: 192.168.1.202
  ports:
    - port: 1900
      targetPort: 1900
      protocol: UDP
      name: udp0
    - port: 5353
      targetPort: 5353
      protocol: UDP
      name: udp1
    - port: 32410
      targetPort: 32410
      protocol: UDP
      name: udp2
    - port: 32412
      targetPort: 32412
      protocol: UDP
      name: udp3
    - port: 32413
      targetPort: 32413
      protocol: UDP
      name: udp4
    - port: 32414
      targetPort: 32414
      protocol: UDP
      name: udp5
