---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-web
  labels:
    app: nc

spec:
  replicas: 1  
  
  selector: 
    matchLabels:
      app: nextcloud

  template:
    metadata:
      labels:
        app: nextcloudd
    
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:20.0.2-apache
          #env:
          #  - name:
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-web-storage
              mountPath: /var/www/html
        
              #- name: nextcloud-sql
          

      volumes:
        - name: nextcloud-web-storage
          persistentVolumeClaim:
            claimName: nextcoud-web-nfs-pvc

