---
# Notes:
# To use the secret you will need to make a new secret and store your value in it
# >kubectl create secret generic SecretNameHere
# You will now need to take your secret that you want to store and convert it to base64
# > echo "yourSecret" | base64
# Copy the output to your clipboard
# > kubectl edit secret SecretKeyName
# Append the following to the bottom of the file.
# data:
#   url: base64CodeHere
#
# Save it

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-newsbot01-backup
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: jtom38/cron-backup:0.0.8
            imagePullPolicy: IfNotPresent
            args:
            - python3
            - /scripts/backup.py
            env:
              - name: BACKUP_JOB
                value: 'newsbot01-config'
              - name: BACKUP_SOURCE
                value: '/app/mounts/database'
              - name: BACKUP_DEST
                value: '/backup'
              - name: BACKUP_USERNAME
                value: 'Kubernetes'
              - name: BACKUP_MAXAGEDAYS
                value: '30'
              - name: BACKUP_DEBUG
                value: 'true'
              - name: BACKUP_WEBHOOK
                valueFrom:
                  secretKeyRef:
                    name: discord-alerts-url
                    key: url
            volumeMounts:
              - name: data
                mountPath: /app/mounts/database
              - name: backup
                mountPath: /backup
          restartPolicy: Never

          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: newsbot01-db-pvc 
            - name: backup
              persistentVolumeClaim:
                claimName: newsbot01-db-backup-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: newsbot01-db-backup-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: newsbot01-db-backup
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: newsbot01-db-backup
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: newsbot01-db-backup
  nfs:
    path: /kube/backup/
    server: 192.168.1.85
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sn02


