# This is using a local path because of SQLite
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: newsbot01-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: newsbot01-config

  local:
    path: /kube/newsbot/01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sn02


