---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: newsbot01-config-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: newsbot01-config
  resources:
    requests:
      storage: 10Gi


