---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nextcloud-pv

spec:
  capacity:
    storage: 10Gi
  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /kube/volumes/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-worker-01

----

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcoud-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

