---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nextcloud-nfs-pv

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  #  mountOptions:
  #  - hard
  #  - nfsvers=4.1
  nfs:
    path: /kube/nextcloud
    server: 192.168.1.85

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-nfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs

