---
apiVersion: v1
kind: Service

metadata:
  name: nextcloud-service

spec:
  selector:
    app: nc      
  
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
      nodePort: 30001


