---
apiVersion: v1
kind: Service

metadata:
  name: nc-service

spec:
  selector:
    app: nc-web 
  
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
      nodePort: 30001


