---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-back-get-data

spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-back-get-data

  nfs:
    path: /mnt/data/kube/media/back/get/data
    server: 192.168.1.222

