---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: jenkins-data
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-jobs-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: jenkins-jobs
  resources:
    requests:
      storage: 10Gi


