---
apiVersion: v1
kind: Service

metadata:
  name: jenkins

spec:
  selector:
    app: jenkins
  
  type: NodePort
  #externalIPs:
  # - 192.168.1.221
  #externalTrafficPolicy: Local
  ports:
    - name: node-communication
      port: 50000
      targetPort: 50000
      nodePort: 31003
      protocol: TCP
    
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30003
      protocol: TCP
    
