---
apiVersion: v1
kind: Service

metadata:
  name: media-search
  labels:
    app: media-search

spec:
  selector:
    app: media-search
  
  type: ClusterIP
  ports:
    - name: ui
      port: 5076
      targetPort: 5076
      #nodePort: 30003
      protocol: TCP
    
---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: media-search-access
  
spec:
  selector:
    app: media-search

    #type: NodePort
  type: LoadBalancer
  loadBalancerIP: 192.168.1.251
  ports:
    - port: 80
      targetPort: 5076
      #nodePort: 30003
      protocol: TCP



