---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: valheim-data

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: valheim-data
  nfs:
    path: /mnt/data/valheim/world01/data
    server: 192.168.1.222
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: valheim-data
  resources:
    requests:
      storage: 10Gi


---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: valheim-config

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: valheim-config
  nfs:
    path: /mnt/data/valheim/world01/config
    server: 192.168.1.222
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-config-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: valheim-config
  resources:
    requests:
      storage: 10Gi


