---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: valheim-access-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: valheim-world01-svc

spec:
  selector:
    app: valheim-world01
  #loadBalancerIP: 192.168.1.201
  type: LoadBalancer
  ports:
    - port: 2456
      targetPort: 2456
      protocol: UDP
      name: access01
    - port: 2457
      targetPort: 2457
      protocol: UDP
      name: access02
    - port: 2458
      targetPort: 2458
      protocol: UDP
      name: access03
