---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-get
  labels:
    app: media-get

spec:
  replicas: 1

  selector:
    matchLabels:
      app: media-get

  template:
    metadata:
      labels:
        app: media-get

    spec:
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
        - name: media-get
          #image: linuxserver/nzbget:v21.0-ls48
          image: linuxserver/nzbget:amd64-v21.1-ls90
          ports:
              #- name: ui
            - containerPort: 6789
              protocol: TCP

          volumeMounts:
            - name: media-get-config
              mountPath: /config
            - name: media-download
              mountPath: /downloads
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "900Mi"
              cpu: "500m"
              
      # Force the pod to use external DNS
      dnsConfig:
        nameservers:
          - 8.8.8.8
      priorityClassName: high-priority
      volumes:
        - name: media-get-config
          persistentVolumeClaim:
            claimName: media-get-config-pvc
        - name: media-download
          persistentVolumeClaim:
            claimName: media-get-download-pvc



