---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nc-web-data-pv
  labels:
    app: web
    storage: nfs
    service: web
    name: nc-web-pv
  #app: nextcloud
  #service: web

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nc-web-data
  nfs: 
    path: /mnt/data/nextcloud/web/data
    server: 192.168.1.222

---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nc-web-config-pv
  labels:
    app: web
    storage: nfs
    service: web
    name: nc-web-pv
  #app: nextcloud
  #service: web

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nc-web-config
  nfs: 
    path: /mnt/data/nextcloud/web/config
    server: 192.168.1.222
 
