---
apiVersion: v1
kind: Service

metadata:
  name: nc-web

spec:
  selector:
    app: nc-web 
 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web-access



