---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-rad-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-rad-config

  #nfs:
  #  path: /mnt/data/media/son/config
  #  server: 192.168.1.222

  local:
    path: /kube/rad/config

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sn01

---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-rad-download

spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-rad-download
  nfs:
    path: /mnt/data/media/download
    server: 192.168.1.222

---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-rad-content

spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-rad-plex-content
  nfs:
    path: /Plex/
    server: 192.168.1.85


