---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-rad-config-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-rad-config
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-rad-download-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-rad-download
  resources:
    requests:
      storage: 100Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-rad-content-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-rad-plex-content
  resources:
    requests:
      storage: 10Ti


