---
apiVersion: v1
kind: Service

metadata:
  name: media-rad
  labels:
    app: media-rad

spec:
  selector:
    app: media-rad
  
  type: ClusterIP
  ports:
    - name: ui
      port: 7878
      targetPort: 7878
      protocol: TCP
    
---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: media-rad-access
  
spec:
  selector:
    app: media-rad

  type: LoadBalancer
  #  loadBalancerIP: 192.168.1.253
  ports:
    - port: 80
      targetPort: 7878
      protocol: TCP

