---
#  This service lets you access the web ui from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: newsbot01-access-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: newsbot01-access-tcp

spec:
  selector:
    app: newsbot-api-01
  loadBalancerIP: 192.168.1.204
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: access01
