---

apiVersion: v1
kind: PersistentVolume

metadata:
  name: jenkins-data

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-data

  # This is used for local development
  #hostPath:
  #  path: /Users/jamestombleson/kube/jenkins/data
  #  type: Directory

  nfs:
    path: /mnt/data/jenkins/data
    server: 192.168.1.222
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sn02
          - k8sn03
          - k8sn04


#---
#apiVersion: v1
#kind: PersistentVolume
#
#metadata:
#  name: jenkins-jobs
#
#spec:
#  capacity:
#    storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: jenkins-jobs

  # This is used for local development
  #hostPath:
  #  path: /Users/jamestombleson/kube/jenkins/data
  #  type: Directory
#  nfs:
#    path: /mnt/data/jenkins/jobs
#    server: 192.168.1.222

---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: jenkins-backup

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-backup

  # This is used for local development
  #hostPath:
  #  path: /Users/jamestombleson/kube/jenkins/data
  #  type: Directory

  nfs:
    path: /kube/backup/jenkins-jobs
    server: 192.168.1.85

