---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-son
  labels:
    app: media-son

spec:
  replicas: 1

  selector:
    matchLabels:
      app: media-son

  template:
    metadata:
      labels:
        app: media-son

    spec:
      containers:
        - name: media-son
          image: linuxserver/sonarr:version-2.0.0.5344
          ports:
              #- name: ui
            - containerPort: 8989
              protocol: TCP

          volumeMounts:
            - name: media-son-config
              mountPath: /config

            - name: media-download
              mountPath: /downloads
            - name: media-content
              mountPath: /tv
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      priorityClassName: high-priority
      volumes:
        - name: media-son-config
          persistentVolumeClaim:
            claimName: media-son-config-pvc
        - name: media-download
          persistentVolumeClaim:
            claimName: media-son-download-pvc
        - name: media-content
          persistentVolumeClaim:
            claimName: media-son-content-pvc

