---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-son-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-son-config

  #nfs:
  #  path: /mnt/data/media/son/config
  #  server: 192.168.1.222

  local:
    path: /kube/son/config
    
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sn01

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-son-config-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-son-config
  resources:
    requests:
      storage: 10Gi
