---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-son-content

spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-plex-content
  nfs:
    path: /Plex/
    server: 192.168.1.85


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-son-content-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-plex-content
  resources:
    requests:
      storage: 10Ti
