---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-son-download

spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-download
  
  nfs:
    path: /mnt/data/media/download
    server: 192.168.1.222

  # this is deployed by ansible
  #local:
  #  path: /kube/son/config
    
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sn01

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-son-download-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-download
  resources:
    requests:
      storage: 100Gi

